version: "3"

services:
  php:
    build: .
    container_name: symfony_start-php
    volumes:
      - .:/var/www
    ports:
      - 80:80
##TODO запилить сюды nginx, а то не могу подключитсья к серверу Symfony через контейнер