version: "3"

services:
  php:
    build: .
    container_name: symfony_start-php
    volumes:
      - .:/var/www
    ports:
      - 80:80
  database:
    container_name: symfony_start-post
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: main
    ports: [5432]



##TODO запилить сюды nginx, а то не могу подключитсья к серверу Symfony через контейнер